### PR TITLE
PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by alekseykuleshov**
Hello @ironkeith !

Adding one more error code to be handled, got this for real transaction.

### CODE REVIEW

**Comment by alekseykuleshov** [comment]
@ironkeith That would be good, I would be able to switch back to your lib (specific version with this fix included) instead my fork in my composer file. Thank you!

**Comment by alekseykuleshov** [comment]
Hello @ironkeith !

I've added one more change here so that the lib is compatible with php 7.4

Could you please merge this one in and do a new release?

**Comment by alekseykuleshov** [comment]
@ironkeith Could you please have a look here? This update is important for us to update our environment.

**Comment by ironkeith** [comment]
Hey @alekseykuleshov, I just cut a new release. Do you want collab permissions on this repo so that I'm not in your way? You've made every commit since 2017 😉

**Pull request merged**
